### PR TITLE
Bump crud version requirements

### PR DESCRIPTION
**Pull request by Spriz**
Since https://github.com/FriendsOfCake/crud/releases/tag/5.0.0

### CODE REVIEW

**Comment by ADmad** [comment]
You'll also need `"phpunit/phpunit":"<6.0"` to get the test suite to run without issues on all PHP versions.

**Comment by ADmad** [comment]
Please rebase onto upstream/master

**Comment by Spriz** [comment]
Ah didn't get to @ADmad.

**Comment by Spriz** [comment]
I see that crud-view has `"crud": "*"` rather - so you might want to do that for consistency?

**Pull request merged**
