### PR TITLE
Add ResetPassword action.

### PR DESCRIPTION
**Pull request by ADmad**
This is intended to replace the `ChangePasswordAction` that was recently added which has a few serious issues:

- It takes `$id` as param which actually never gets used. Also for resetting password you aren't going to have id in request url anyway.
- It's `_get()` always fetches the first record for table and doesn't even trigger a `beforeFind` to allow modifying the query.
- I am not really happy with the `beforeVerify` and `afterVerify` events. If one fails to properly modify the query you would end up with the first record of table always being fetched which could be problematic.

### CODE REVIEW

**Comment by ADmad** [comment]
This is how it works:

- GET /users/reset-password
    - Get token from request and use it to get user entity and to view which shows form to enter new password

- POST /users/reset-password
    - Using the token find appropriate user record. By default it queries the table with condition `['token' => $token]`. Token is also passed using `token` key in options so that you can use it in your custom finder.
    - If no record is found a `tokenNotFound` exception is thrown.
    - A `verifyToken` event is triggered. You are excepted to do required checks like check token expiry and set `$subject->verfied` to `true` (Default is false) to indicate success.
    - If `$subject->verfied is not `true` then `tokenExpired` exception is thrown.
    - On success user entity is patched with request save and saved with new password.
    - `afterResetPassword` event is triggered which would normally be used to reset the token for that user record.

**Comment by jippi** [comment]
👍

**Comment by Phillaf** [comment]
I tested this PR with a couple use cases and it's great. One thing that I wish was possible would be to verify the token in the GET request. This could be used for simple email address verification.

it could be made possible by adding something like this at the end of the __get() method

```
if ($this->config('validateOnly')) {
    return $this->_put($token);
}
```

**Comment by lorenzo** [comment]
cool stuff!

**Comment by ADmad** [comment]
@Phillaf You intend to use it for email verification when registering new users?

**Comment by Phillaf** [comment]
exactly

**Comment by ADmad** [comment]
It would be better to save a separate action for that and then move the verification code in a trait for reuse in both actions.

**Comment by Phillaf** [comment]
make sense

**Pull request merged**
